const data = [
	{ value: 'banja-luka', label: 'Banja Luka'},
	{ value: 'bihac', label: 'Bihać'},
	{ value: 'bijeljina', label: 'Bijeljina'},
	{ value: 'bosanska-krupa', label: 'Bosanska Krupa'},
	{ value: 'brcko', label: 'Brčko'},
	{ value: 'bugojno', label: 'Bugojno'},
	{ value: 'cazin', label: 'Cazin'},
	{ value: 'derventa', label: 'Derventa'},
	{ value: 'doboj', label: 'Doboj'},
	{ value: 'foca', label: 'Foča'},
	{ value: 'gorazde', label: 'Goražde'},
	{ value: 'gradacac', label: 'Gradačac'},
	{ value: 'gradiska', label: 'Gradiška'},
	{ value: 'gracanica', label: 'Gračanica'},
	{ value: 'jajce', label: 'Jajce'},
	{ value: 'kakanj', label: 'Kakanj'},
	{ value: 'kalesija', label: 'Kalesija'},
	{ value: 'konjic', label: 'Konjic'},
	{ value: 'kozarska-dubica', label: 'Kozarska Dubica'},
	{ value: 'laktasi', label: 'Laktaši'},
	{ value: 'livno', label: 'Livno'},
	{ value: 'lukavac', label: 'Lukavac'},
	{ value: 'modrica', label: 'Modriča'},
	{ value: 'mostar', label: 'Mostar'},
	{ value: 'novi-grad', label: 'Novi Grad'},
	{ value: 'novi-travnik', label: 'Novi Travnik'},
	{ value: 'pale', label: 'Pale'},
	{ value: 'prijedor', label: 'Prijedor'},
	{ value: 'prnjavor', label: 'Prnjavor'},
	{ value: 'sanski-most', label: 'Sanski Most'},
	{ value: 'sarajevo', label: 'Sarajevo'},
	{ value: 'srebrenik', label: 'Srebrenik'},
	{ value: 'teslic', label: 'Teslić'},
	{ value: 'tesanj', label: 'Tešanj'},
	{ value: 'tomislavgrad', label: 'Tomislavgrad'},
	{ value: 'travnik', label: 'Travnik'},
	{ value: 'trebinje', label: 'Trebinje'},
	{ value: 'tuzla', label: 'Tuzla'},
	{ value: 'velika-kladusa', label: 'Velika Kladuša'},
	{ value: 'visoko', label: 'Visoko'},
	{ value: 'vitez', label: 'Vitez'},
	{ value: 'vogosca', label: 'Vogošća'},
	{ value: 'zavidovici', label: 'Zavidovići'},
	{ value: 'zenica', label: 'Zenica'},
	{ value: 'zvornik', label: 'Zvornik'},
	{ value: 'siroki-brijeg', label: 'Široki Brijeg'},
	{ value: 'zepce', label: 'Žepče'},
	{ value: 'zivinice', label: 'Živinice'},
];

export default data;
